# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QGIS2FDS
                                 A QGIS plugin
 Export terrain in NIST FDS notation
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-05-04
        copyright            : (C) 2020 by Emanuele Gissi
        email                : emanuele.gissi@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Emanuele Gissi'
__date__ = '2020-05-04'
__copyright__ = '(C) 2020 by Emanuele Gissi'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QGIS2FDS class from file QGIS2FDS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .QGIS2FDS import QGIS2FDSPlugin
    return QGIS2FDSPlugin()
